### ISSUE TITLE
Make it easier to do activity req. URL mapping

### ISSUE THREAD

**Issue by McDKirra** [mikezimm/TrackMyTime#48]
@mikezimm - I just want to type a sentence and put in the variables: 

### This is what you have to do: 
```typescript
commentTextMapping: 'childFolderTitle, parentFolderTitle' ,
```

### This is what I want it to do: 
```typescript
commentTextMapping: 'The following Item: childFolderTitle, parentFolderTitle has been changed' ,
```

**Comment by mikezimm** [comment]
I made an update... PR #49 that should close this request!
